const ANIME_CACHE_KEY='animeSpaceApiCache:v4';
const ANIME_CACHE_TTL=7*24*60*60*1000;
const ANILIST_API='https://graphql.anilist.co';
const ANIME_API='https://anime-space-5oftlp527-anime-space.vercel.app/api/anime';
const SUPABASE_URL='https://vbxjvwssjafcfbmqrqow.supabase.co';
const SUPABASE_KEY='sb_publishable__5mPBElGBo1GFn7Yd0n4Ng_1i28p6aE';
function getAnimeCache(){try{return JSON.parse(localStorage.getItem(ANIME_CACHE_KEY)||'{}')}catch{return {}}}
function getCachedAnime(key){const x=getAnimeCache()[key];return x&&Date.now()-x.savedAt<ANIME_CACHE_TTL?x.data:null}
function cacheAnime(key,data){if(!data)return;try{const c=getAnimeCache();c[key]={savedAt:Date.now(),data};localStorage.setItem(ANIME_CACHE_KEY,JSON.stringify(c))}catch{}}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function packAnime(a){return encodeURIComponent(JSON.stringify(a)).replace(/'/g,'%27')}
function animeStatusKey(a){return String(a?.title||'').trim().toLowerCase()+'|'+String(a?.image||'').trim()}
function statusStorageKey(id){return 'animeSpaceStatuses:'+id}
function getStatuses(id){try{return JSON.parse(localStorage.getItem(statusStorageKey(id))||'{}')}catch{return {}}}
function russianTitle(a){const syn=(a.synonyms||[]).find(x=>/[А-Яа-яЁё]/.test(x));return syn||a.title?.userPreferred||a.title?.english||a.title?.romaji||a.title?.native||'Без названия'}
function normalizeAnime(a){if(!a)return null;const image=a.coverImage?.extraLarge||a.coverImage?.large||a.coverImage?.medium||a.image?.original||a.image?.preview||a.image||a.poster?.originalUrl||'';return {id:a.id,title:russianTitle(a),image,rating:a.averageScore?Number(a.averageScore/10).toFixed(1):(a.score?Number(a.score/10).toFixed(1):(a.rating??'—')),year:a.startDate?.year||a.year||null,episodes:a.episodes||0,status:a.status||'',duration:a.duration||0,genres:(a.genres||[]).map(g=>g.russian||g.name||g).filter(Boolean),description:a.description||''}}
async function aniList(query,variables={}){const r=await fetch(ANILIST_API,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({query,variables}),cache:'no-store'});if(!r.ok)throw new Error('AniList API: '+r.status);const json=await r.json();if(json.errors?.length)throw new Error(json.errors[0].message||'AniList API error');return json.data}
const MEDIA_FIELDS=`id title { romaji english native userPreferred } synonyms coverImage { extraLarge large medium } averageScore startDate { year } episodes status duration genres description`;
async function shikimori(path,params={}){let type=path==='/calendar'?'schedule':path.startsWith('/animes/')?'details':params.search?'search':params.order==='popularity'?'popular':params.order==='aired_on'?'new':'top';if(type==='details'){const data=await aniList(`query($id:Int){Media(id:$id,type:ANIME){${MEDIA_FIELDS}}}`,{id:Number(path.split('/').pop())});return data.Media||null}if(type==='schedule')return [] ;const perPage=Math.min(Number(params.limit)||20,100),page=Number(params.page)||1;let sort=type==='top'||type==='search'?'SCORE_DESC':type==='new'?'START_DATE_DESC':'POPULARITY_DESC';const data=await aniList(`query($page:Int,$perPage:Int,$search:String,$sort:[MediaSort]){Page(page:$page,perPage:$perPage){media(type:ANIME,search:$search,sort:$sort,isAdult:false){${MEDIA_FIELDS}}}}`,{page,perPage,search:params.search||null,sort:[sort]});return data.Page.media||[]}
async function getAnimes(params={}){const key='list:'+JSON.stringify({limit:params.limit||20,page:params.page||1,order:params.order||'ranked',search:params.search||''});const cached=getCachedAnime(key);if(cached)return cached;try{const data=await shikimori('/animes',{limit:params.limit||20,page:params.page||1,order:params.order||'ranked',search:params.search});const list=Array.isArray(data)?data.map(normalizeAnime).filter(Boolean):[];if(list.length)cacheAnime(key,list);return list}catch(e){if(cached)return cached;throw e}}
async function getAnime(id){const cached=getCachedAnime('id:'+id);if(cached)return cached;try{const a=normalizeAnime(await shikimori('/animes/'+encodeURIComponent(id)));if(a)cacheAnime('id:'+id,a);return a}catch(e){if(cached)return cached;throw e}}
function renderApiRow(id,list){const el=document.getElementById(id);if(!el)return;el.innerHTML=(list||[]).map(a=>{cacheAnime(animeStatusKey(a),a);return `<article class="anime-card" data-anime='${packAnime(a)}'><img src="${esc(a.image)}" alt="${esc(a.title)}" loading="lazy" onerror="this.onerror=null;this.style.visibility='hidden'"><div class="info"><div class="title">${esc(a.title)}</div><div class="rating">${esc(a.rating)}</div></div></article>`}).join('')}
function renderCachedHome(){const c=getAnimeCache();[['popular','popularity'],['newAnime','aired_on'],['rated','ranked'],['recommendations','recommendations']].forEach(([id,type])=>{const el=document.getElementById(id);if(!el)return;let best=[];for(const x of Object.values(c)){if(!Array.isArray(x.data))continue;const list=x.data;if(type==='recommendations')best=best.concat(list);else if(String(x.dataKey||'').includes(type))best=best.concat(list)}if(!best.length)best=Object.values(c).filter(x=>Array.isArray(x.data)).flatMap(x=>x.data);const seen=new Set();best=best.filter(a=>a?.id&&!seen.has(a.id)&&(seen.add(a.id),a.image)).slice(0,6);if(best.length)renderApiRow(id,best)})}
async function loadHomeFromApi(){renderCachedHome();try{const results=await Promise.allSettled([getAnimes({limit:6,order:'popularity'}),getAnimes({limit:6,order:'aired_on'}),getAnimes({limit:6,order:'ranked'}),getAnimes({limit:6,order:'popularity',page:2})]);const [popular,newAnime,rated,recommendations]=results.map(r=>r.status==='fulfilled'?r.value:[]);if(popular.length)renderApiRow('popular',popular);if(newAnime.length)renderApiRow('newAnime',newAnime);if(rated.length)renderApiRow('rated',rated);if(recommendations.length)renderApiRow('recommendations',recommendations)}catch(e){console.error('AnimeSpace home API error:',e)}}
async function loadTopFromApi(){const grid=document.getElementById('topGrid'),podium=document.getElementById('podium');if(!grid&&!podium)return;try{const list=await getAnimes({limit:100,order:'ranked'});const make=(a,i)=>`<article class="top-card" data-anime='${packAnime(a)}'><img src="${esc(a.image)}" alt="${esc(a.title)}" loading="lazy"><div class="top-info"><div class="top-rank">#${i}</div><div class="top-name">${esc(a.title)}</div><div class="top-rating">★ ${esc(a.rating)}</div><div class="top-meta">${a.episodes||'—'} эпизода · ${esc(a.status||'—')}</div></div></article>`;if(podium)podium.innerHTML=list.slice(0,3).map((a,i)=>make(a,i+1)).join('');if(grid)grid.innerHTML=list.slice(3).map((a,i)=>make(a,i+4)).join('')}catch(e){console.error('AnimeSpace top API error:',e)}}
async function loadScheduleFromApi(){const grid=document.getElementById('grid');if(!grid)return;try{const response=await fetch(ANIME_API+'?type=schedule&_='+Date.now(),{cache:'no-store',headers:{Accept:'application/json','Cache-Control':'no-cache'}});if(!response.ok)throw new Error('Schedule API: '+response.status);const raw=await response.json();window.animeSpaceSchedule=Array.isArray(raw)?raw:[];if(typeof window.animeSpaceRenderSchedule==='function')window.animeSpaceRenderSchedule()}catch(e){console.error('AnimeSpace schedule API error:',e)}}
async function searchShikimori(query){return query?getAnimes({search:query,limit:30,order:'ranked'}):[]}
function applyStatuses(userId){const statuses=getStatuses(userId);document.querySelectorAll('.anime-card,.top-card,.schedule-card').forEach(c=>{let data;try{data=JSON.parse(decodeURIComponent(c.dataset.anime||''))}catch{}if(!data)data={title:c.querySelector('.title,.top-name,.schedule-name')?.textContent.trim()||'',image:c.querySelector('img')?.src||''};c.classList.remove('status-plan','status-watching','status-done','status-dropped');const s=statuses[animeStatusKey(data)];if(s)c.classList.add({plan:'status-plan',watching:'status-watching',done:'status-done',dropped:'status-dropped'}[s]||'')})}
document.addEventListener('click',e=>{const c=e.target.closest('.anime-card,.top-card,.schedule-card,.popular-search-card');if(!c)return;let data;try{data=JSON.parse(decodeURIComponent(c.dataset.anime||''))}catch{}if(!data)return;cacheAnime(animeStatusKey(data),data);localStorage.setItem('selectedAnime',JSON.stringify(data));location.href='anime-details.html'});
(function(){
 function findProfileNav(){const nav=document.querySelector('.nav');if(!nav)return null;let p=nav.querySelector('#profileNav')||nav.querySelector('a.profile-nav')||nav.querySelector('a[href="profile.html"]');if(!p){p=document.createElement('a');p.href='profile.html';p.className='profile-nav';nav.appendChild(p)}p.classList.add('profile-nav');p.id='profileNav';let icon=p.querySelector('#profileNavIcon,.icon');if(!icon){icon=document.createElement('span');icon.className='icon';p.prepend(icon)}icon.id='profileNavIcon';let text=p.querySelector('#profileNavText,.profile-nav-text');if(!text){text=document.createElement('span');p.appendChild(text)}text.id='profileNavText';text.className='profile-nav-text';return {p,icon,text}}
 const refs=findProfileNav();if(!refs)return;const {p,icon,text}=refs;
 function defaultIcon(){return '<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 21c.7-4 3.1-6 7-6s6.3 2 7 6"/></svg>'}
 function getStoredAvatar(user){if(user){const a=localStorage.getItem('animeSpaceAvatar:'+user.id);if(a)return a}for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.indexOf('animeSpaceAvatar:')===0){const a=localStorage.getItem(k);if(a)return a}}return null}
 function paint(user){if(!user){p.href='login.html';p.classList.add('login-state');p.classList.remove('has-avatar');icon.innerHTML='';text.textContent='Войти';return}p.href='profile.html';p.classList.remove('login-state');const a=getStoredAvatar(user);if(a){p.classList.add('has-avatar');icon.innerHTML='<img src="'+a+'" alt="Аватар">';text.textContent=''}else{p.classList.remove('has-avatar');icon.innerHTML=defaultIcon();text.textContent='Профиль'}}
 async function init(){try{let client=window.__animeSpaceSupabaseClient;if(!client){if(!window.supabase){return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});window.__animeSpaceSupabaseClient=client}const sessionResult=await client.auth.getSession();const session=sessionResult.data?.session;if(session?.user){paint(session.user);applyStatuses(session.user.id)}else{const userResult=await client.auth.getUser();if(userResult.data?.user){paint(userResult.data.user);applyStatuses(userResult.data.user.id)}else{const avatar=getStoredAvatar(null);if(avatar){p.href='profile.html';p.classList.remove('login-state');p.classList.add('has-avatar');icon.innerHTML='<img src="'+avatar+'" alt="Аватар">';text.textContent=''}else paint(null)}}client.auth.onAuthStateChange((event,s)=>{if(event==='SIGNED_OUT')paint(null);else if(s?.user){paint(s.user);applyStatuses(s.user.id)}})}catch(e){console.warn('AnimeSpace auth:',e);const avatar=getStoredAvatar(null);if(avatar){p.href='profile.html';p.classList.remove('login-state');p.classList.add('has-avatar');icon.innerHTML='<img src="'+avatar+'" alt="Аватар">';text.textContent=''}else paint(null)}}
 init();
})();
loadHomeFromApi();loadTopFromApi();loadScheduleFromApi();
