const images=['https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1560972550-aba3456b5564?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1613376023733-0a73315d9b06?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=700&q=80','https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=700&q=80'];
const sets={recommendations:[['Рекомендуемое аниме','8.7'],['Новая история','8.5'],['Лучший выбор','9.0'],['Тёмный мир','8.3'],['Новая глава','8.9'],['Герои','8.6']],popular:[['Популярное #1','9.2'],['Популярное #2','9.0'],['Популярное #3','8.9'],['Популярное #4','8.8'],['Популярное #5','8.7'],['Популярное #6','8.6']],newAnime:[['Новая серия','8.8'],['Свежий релиз','8.6'],['Новый сезон','8.5'],['Премьера','8.4'],['Новая история','8.3'],['Новый герой','8.2']],rated:[['Лучший рейтинг','9.8'],['Золотая коллекция','9.7'],['Фаворит зрителей','9.6'],['Легендарная история','9.5'],['Любимец публики','9.4'],['Главный фаворит','9.3']]};
const ANIME_CACHE_KEY='animeSpaceApiCache:v1';
const ANIME_CACHE_TTL=24*60*60*1000;
const ANIME_BACKEND='https://anime-space-i87nw1j1v-anime-space.vercel.app/api/anime';
function getAnimeCache(){try{return JSON.parse(localStorage.getItem(ANIME_CACHE_KEY)||'{}')}catch{return {}}}
function getCachedAnime(key){const cache=getAnimeCache();const item=cache[key];if(!item||Date.now()-item.savedAt>ANIME_CACHE_TTL)return null;return item.data}
function cacheAnime(key,data){if(!data)return;try{const cache=getAnimeCache();cache[key]={savedAt:Date.now(),data:{id:data.id??null,title:data.title||'',image:data.image||'',year:data.year??null,rating:data.rating??null,duration:data.duration??null,episodes:data.episodes??null,status:data.status??null,genres:data.genres??[],description:data.description??''}};localStorage.setItem(ANIME_CACHE_KEY,JSON.stringify(cache))}catch{}}
function esc(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function animeStatusKey(anime){return String(anime?.title||'').trim().toLowerCase()+'|'+String(anime?.image||'').trim()}
function statusStorageKey(userId){return 'animeSpaceStatuses:'+userId}
function getStatuses(userId){try{return JSON.parse(localStorage.getItem(statusStorageKey(userId))||'{}')}catch{return {}}}
function card(name,rating,i){const anime={title:name,rating,image:images[i%images.length]};cacheAnime(animeStatusKey(anime),anime);return `<article class="anime-card" data-anime='${encodeURIComponent(JSON.stringify(anime))}'><img src="${images[i%images.length]}" alt="${esc(name)}" loading="lazy"><div class="info"><div class="title">${esc(name)}</div><div class="rating">${esc(rating)}</div></div></article>`}
function fill(id,list,offset=0){const el=document.getElementById(id);if(el)el.innerHTML=list.map((x,i)=>card(x[0],x[1],i+offset)).join('')}
fill('recommendations',sets.recommendations);fill('popular',sets.popular);fill('newAnime',sets.newAnime,2);fill('rated',sets.rated,3);
function normalizeAnime(a){if(!a)return null;const image=a.image?.original||a.image?.preview||a.image?.x96||a.poster?.originalUrl||a.poster?.main2xUrl||a.poster?.previewUrl||'';const year=a.aired_on?new Date(a.aired_on).getFullYear():null;return{id:a.id,title:a.russian||a.name||a.title||'Без названия',image,rating:a.score?Number(a.score).toFixed(1):(a.rating??'—'),year:year||a.year||null,episodes:a.episodes||0,status:a.status||'',duration:a.duration||0,genres:(a.genres||[]).map(g=>g.russian||g.name||g).filter(Boolean),description:a.description||''}}
async function shikimori(path,params={}){let type='';let extra={};if(path==='/calendar'){type='schedule'}else if(path.startsWith('/animes/')){type='details';extra.id=path.split('/').pop()}else{if(params.search)type='search';else if(params.order==='popularity')type='popular';else if(params.order==='aired_on')type='new';else type='top';extra={q:params.search,page:params.page,limit:params.limit}}const url=new URL(ANIME_BACKEND);url.searchParams.set('type',type);Object.entries(extra).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,v)});const r=await fetch(url);if(!r.ok)throw new Error('AnimeSpace API: '+r.status);return r.json()}
async function getAnimes(params={}){const data=await shikimori('/animes',{limit:params.limit||20,page:params.page||1,order:params.order||'ranked',search:params.search,season:params.season,status:params.status,kind:params.kind});return Array.isArray(data)?data.map(normalizeAnime).filter(Boolean):[]}
async function getAnime(id){const cached=getCachedAnime('id:'+id);if(cached)return cached;const data=normalizeAnime(await shikimori('/animes/'+encodeURIComponent(id)));if(data)cacheAnime('id:'+id,data);return data}
async function loadHomeFromApi(){try{const [popular,newAnime,rated,recommendations]=await Promise.all([getAnimes({limit:6,order:'popularity'}),getAnimes({limit:6,order:'aired_on'}),getAnimes({limit:6,order:'ranked'}),getAnimes({limit:6,order:'random'})]);renderApiRow('popular',popular);renderApiRow('newAnime',newAnime);renderApiRow('rated',rated);renderApiRow('recommendations',recommendations)}catch(e){console.warn(e)}}
function renderApiRow(id,list){const el=document.getElementById(id);if(!el||!list.length)return;el.innerHTML=list.map(a=>{cacheAnime(animeStatusKey(a),a);return `<article class="anime-card" data-anime='${encodeURIComponent(JSON.stringify(a))}'><img src="${esc(a.image)}" alt="${esc(a.title)}" loading="lazy"><div class="info"><div class="title">${esc(a.title)}</div><div class="rating">${esc(a.rating)}</div></div></article>`}).join('')}
async function loadTopFromApi(){const grid=document.getElementById('topGrid');const podium=document.getElementById('podium');if(!grid&&!podium)return;try{const list=await getAnimes({limit:100,order:'ranked'});const make=(a,i)=>`<article class="top-card" data-anime='${encodeURIComponent(JSON.stringify(a))}'><img src="${esc(a.image)}" alt="${esc(a.title)}" loading="lazy"><div class="top-info"><div class="top-rank">#${i}</div><div class="top-name">${esc(a.title)}</div><div class="top-rating">★ ${esc(a.rating)}</div><div class="top-meta">${a.episodes||'—'} эпизода · ${esc(a.status||'—')}</div></div></article>`;if(podium)podium.innerHTML=list.slice(0,3).map((a,i)=>make(a,i+1)).join('');if(grid)grid.innerHTML=list.slice(3).map((a,i)=>make(a,i+4)).join('')}catch(e){console.warn(e)}}
async function loadScheduleFromApi(){const grid=document.getElementById('grid');if(!grid)return;try{const data=await shikimori('/calendar');const list=(Array.isArray(data)?data:[]).filter(x=>x.anime).map(x=>{const a=normalizeAnime(x.anime);if(!a)return null;return {...a,episode:x.next_episode||x.episode||null,time:x.next_episode_at||x.time||''}}).filter(Boolean);window.animeSpaceSchedule=list;const renderSchedule=window.animeSpaceRenderSchedule;if(typeof renderSchedule==='function')renderSchedule()}catch(e){console.warn(e)}}
async function searchShikimori(query){if(!query)return[];return getAnimes({search:query,limit:30,order:'ranked'})}
function applyStatuses(userId){const statuses=getStatuses(userId);document.querySelectorAll('.anime-card,.top-card,.schedule-card').forEach(c=>{let data;try{data=JSON.parse(decodeURIComponent(c.dataset.anime||''))}catch{}if(!data){const title=c.querySelector('.title,.top-name,.schedule-name');data={title:title?.textContent.trim()||'',image:c.querySelector('img')?.src||''}}c.classList.remove('status-plan','status-watching','status-done','status-dropped');const s=statuses[animeStatusKey(data)];if(s)c.classList.add({plan:'status-plan',watching:'status-watching',done:'status-done',dropped:'status-dropped'}[s]||'')})}
document.addEventListener('click',e=>{const c=e.target.closest('.anime-card,.top-card,.schedule-card');if(!c)return;let data;try{data=JSON.parse(decodeURIComponent(c.dataset.anime||''))}catch{}if(!data){const title=c.querySelector('.title,.top-name,.schedule-name');const rating=c.querySelector('.rating,.top-rating,.schedule-meta');data={title:title?.textContent.trim()||'Аниме',rating:rating?.textContent.replace('★','').trim()||'—',image:c.querySelector('img')?.src||''}}cacheAnime(animeStatusKey(data),data);localStorage.setItem('selectedAnime',JSON.stringify(data));location.href='anime-details.html'});

(async()=>{const nav=document.querySelector('.nav');if(!nav)return;const old=nav.querySelector('a[href="profile.html"]');if(!old)return;old.classList.add('profile-nav');old.id='profileNav';old.style.display='flex';const icon=old.querySelector('.icon');if(icon)icon.id='profileNavIcon';[...old.childNodes].forEach(node=>{if(node.nodeType===3)node.remove()});let text=old.querySelector('.profile-nav-text');if(!text){text=document.createElement('span');text.className='profile-nav-text';old.appendChild(text)}function showLogin(){old.href='login.html';old.classList.remove('has-avatar');old.classList.add('login-state');if(icon)icon.innerHTML='';text.textContent='Войти'}function showProfile(user){old.href='profile.html';old.classList.remove('login-state');const avatar=localStorage.getItem('animeSpaceAvatar:'+user.id);if(avatar){old.classList.add('has-avatar');if(icon)icon.innerHTML='<img src="'+avatar+'" alt="Аватар">';text.textContent=''}else{old.classList.remove('has-avatar');if(icon)icon.innerHTML='<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 21c.7-4 3.1-6 7-6s6.3 2 7 6"/></svg>';text.textContent='Профиль'}}try{if(!window.supabase){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';document.head.appendChild(s);await new Promise((resolve,reject)=>{s.onload=resolve;s.onerror=reject})}const client=window.supabase.createClient('https://vbxjvwssjafcfbmqrqow.supabase.co','sb_publishable__5mPBElGBo1GFn7Yd0n4Ng_1i28p6aE',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});async function update(){const result=await client.auth.getUser();if(result.error)return;if(result.data.user){showProfile(result.data.user);applyStatuses(result.data.user.id)}else showLogin()}await update();client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')showLogin();else if(session?.user){showProfile(session.user);applyStatuses(session.user.id)}else update()})}catch{if(!text.textContent)text.textContent='Профиль'}})();

loadHomeFromApi();
loadTopFromApi();
loadScheduleFromApi();